services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: scinets
      POSTGRES_USER: scinets
      POSTGRES_PASSWORD: scinets
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scinets -d scinets"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: ./.env
    dns: # <--- ADD THIS LINE
      - 8.8.8.8 # <--- AND THIS LINE
    environment:
      ENVIRONMENT: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: scinets
      POSTGRES_USER: scinets
      POSTGRES_PASSWORD: scinets
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_SECURE: "false"
      QDRANT_URL: http://qdrant:6333
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./Frontend:/app
    command: sh -c "npm install && npm run dev -- --port 3000 --hostname 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  pg_data:
  minio_data:
  qdrant_data:


