from __future__ import annotations

from typing import Any, Awaitable, Callable, Mapping


class Request:
    async def json(self) -> Any: ...


class UploadFile:
    filename: str | None
    content_type: str | None

    async def read(self, n: int | None = ...) -> bytes: ...

    async def close(self) -> None: ...


class BackgroundTasks:
    def add_task(self, func: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...


class FastAPI:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def add_middleware(self, middleware_class: type[Any], **kwargs: Any) -> None: ...

    def middleware(self, middleware_type: str) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]: ...

    def on_event(self, event_type: str) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]: ...

    def get(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]: ...

    def post(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]: ...

    def include_router(self, router: Any, **kwargs: Any) -> None: ...


class APIRouter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def get(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]: ...

    def post(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]: ...

    def put(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]: ...

    def delete(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]: ...

    def include_router(self, router: Any, **kwargs: Any) -> None: ...


class HTTPException(Exception):
    def __init__(self, status_code: int, detail: Any | None = ..., headers: Mapping[str, str] | None = ...) -> None: ...


def Depends(dependency: Any | None = ..., use_cache: bool = ...) -> Any: ...


def Query(default: Any = ..., *args: Any, **kwargs: Any) -> Any: ...


def File(default: Any = ..., *args: Any, **kwargs: Any) -> Any: ...


def Form(default: Any = ..., *args: Any, **kwargs: Any) -> Any: ...

