from app.state import DiscoveryState
from app.llm import get_llm
from langchain_core.messages import HumanMessage, SystemMessage
import json

async def critique_node(state: DiscoveryState) -> dict:
    """
    Critique Agent: Reviews the experiment results (including plots) and concludes the session.
    """
    print("[Critique] Analyzing results...")
    
    if not state.experiments:
        return {"critique": {"summary": "No experiments were run."}}
    
    exp = state.experiments[0]
    metrics = exp.metrics
    plot_b64 = exp.plot_base64
    
    # Prepare the prompt
    messages = [
        SystemMessage(content="You are a senior scientist. Analyze the experiment results and provide a critique and recommendation. If a plot is provided, analyze its visual patterns (trends, convergence, outliers)."),
        HumanMessage(content=f"Hypothesis: {state.hypotheses[0].text if state.hypotheses else 'N/A'}\nMetrics: {json.dumps(metrics)}")
    ]
    
    if plot_b64:
        print("[Critique] Including plot in analysis...")
        messages.append(
            HumanMessage(
                content=[
                    {"type": "text", "text": "Here is the plot generated by the experiment:"},
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:image/png;base64,{plot_b64}"},
                    },
                ]
            )
        )
        
    # Use a vision-capable model (Claude 3.5 Sonnet or GPT-4o)
    # get_llm defaults to Claude 3.5 Sonnet which supports vision
    llm = get_llm(temperature=0.1)
    
    response = await llm.ainvoke(messages)
    critique_text = response.content
    
    # Simple parsing for now (in future, use structured output)
    # We'll just put the whole text in summary
    
    # Store Insight in Memory
    from app.memory import MemoryManager
    from app.state import Insight
    
    try:
        memory = MemoryManager()
        insight = Insight(
            content=critique_text,
            domain=state.domain_tags[0] if state.domain_tags else "general",
            confidence=0.8 # Placeholder
        )
        memory.store_insight(insight)
    except Exception as e:
        print(f"[Critique] Failed to store insight: {e}")

    return {
        "critique": {
            "summary": critique_text,
            "recommendation": "See analysis above."
        },
        "done": True
    }
